WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
SET VERIFY OFF

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM dba_users
    WHERE username = 'NANOORBIT_ADMIN';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER NANOORBIT_ADMIN CASCADE';
    END IF;
END;
/

CREATE USER NANOORBIT_ADMIN IDENTIFIED BY NanoOrbit123;
GRANT CONNECT, RESOURCE TO NANOORBIT_ADMIN;
GRANT CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, CREATE MATERIALIZED VIEW TO NANOORBIT_ADMIN;
ALTER USER NANOORBIT_ADMIN QUOTA UNLIMITED ON USERS;

EXIT SUCCESS
