-- ============================================================================
-- NanoOrbit - Phase 2 - Livrable L2-A
-- Fichier : L2-A_DDL_Tables.sql
-- Objet   : DDL complet (10 tables NanoOrbit + HISTORIQUE_STATUT)
-- SGBD    : Oracle 23ai
-- Schema  : NANOORBIT_ADMIN
-- ============================================================================

-- Choix d'harmonisation retenus :
-- - Les identifiants d'orbite suivent les CSV : 1, 2, 3.
-- - Les identifiants de centre suivent les CSV : 1, 2, 3.
-- - Les valeurs de statut conservent les accents des CSV de reference.
-- - Le centre Singapour fait partie du jeu initial, car il est present dans les CSV.

-- Questions de reflexion Phase 2
-- Q1 : SATELLITE ne peut pas etre creee avant ORBITE car SATELLITE contient
--      une cle etrangere id_orbite vers ORBITE. Cela traduit RG-S02 : chaque
--      satellite est rattache a une orbite courante existante.
-- Q2 : RG-S06 ne peut pas etre verifiee uniquement en DDL, car elle depend
--      de la valeur courante du statut du satellite au moment d'une insertion.
--      La solution retenue est un trigger BEFORE INSERT sur FENETRE_COM.
-- Q3 : RG-F02 ne peut pas etre exprimee par un CHECK, car elle compare la
--      nouvelle ligne aux autres fenetres existantes. La solution retenue est
--      un trigger PL/SQL de controle des chevauchements temporels.
-- Q4 : format_cubesat est stocke en VARCHAR2(5), car les valeurs contiennent
--      une unite textuelle ('1U', '3U', '6U', '12U'). Un CHECK limite le domaine.

-- Ordre de creation impose par les dependances FK :
-- ORBITE -> SATELLITE -> HISTORIQUE_STATUT -> INSTRUMENT -> EMBARQUEMENT
-- -> CENTRE_CONTROLE -> STATION_SOL -> AFFECTATION_STATION -> MISSION
-- -> FENETRE_COM -> PARTICIPATION.

CREATE TABLE ORBITE (
    id_orbite NUMBER(10),
    type_orbite VARCHAR2(10) NOT NULL,
    altitude NUMBER(5) NOT NULL,
    inclinaison NUMBER(5,2) NOT NULL,
    periode_orbitale NUMBER(6,2) NOT NULL,
    excentricite NUMBER(6,4) NOT NULL,
    zone_couverture VARCHAR2(200) NOT NULL,
    CONSTRAINT pk_orbite PRIMARY KEY (id_orbite),
    CONSTRAINT uk_orbite_alt_inc UNIQUE (altitude, inclinaison),
    CONSTRAINT ck_orbite_type CHECK (type_orbite IN ('LEO', 'MEO', 'SSO', 'GEO')),
    CONSTRAINT ck_orbite_altitude CHECK (altitude > 0),
    CONSTRAINT ck_orbite_periode CHECK (periode_orbitale > 0),
    CONSTRAINT ck_orbite_excentricite CHECK (excentricite >= 0 AND excentricite < 1)
);

CREATE TABLE SATELLITE (
    id_satellite VARCHAR2(20),
    nom_satellite VARCHAR2(100) NOT NULL,
    date_lancement DATE NOT NULL,
    masse NUMBER(5,2) NOT NULL,
    format_cubesat VARCHAR2(5) NOT NULL,
    statut VARCHAR2(30) NOT NULL,
    duree_vie_prevue NUMBER(4) NOT NULL,
    capacite_batterie NUMBER(6,1) NOT NULL,
    id_orbite NUMBER(10) NOT NULL,
    CONSTRAINT pk_satellite PRIMARY KEY (id_satellite),
    CONSTRAINT fk_satellite_orbite FOREIGN KEY (id_orbite) REFERENCES ORBITE (id_orbite),
    CONSTRAINT ck_satellite_masse CHECK (masse > 0),
    CONSTRAINT ck_satellite_format CHECK (format_cubesat IN ('1U', '3U', '6U', '12U')),
    CONSTRAINT ck_satellite_statut CHECK (statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité')),
    CONSTRAINT ck_satellite_duree_vie CHECK (duree_vie_prevue > 0),
    CONSTRAINT ck_satellite_batterie CHECK (capacite_batterie > 0)
);

CREATE TABLE HISTORIQUE_STATUT (
    id_historique NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1),
    id_satellite VARCHAR2(20) NOT NULL,
    ancien_statut VARCHAR2(30) NOT NULL,
    nouveau_statut VARCHAR2(30) NOT NULL,
    date_changement TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    motif VARCHAR2(200),
    CONSTRAINT pk_historique_statut PRIMARY KEY (id_historique),
    CONSTRAINT fk_hist_statut_satellite FOREIGN KEY (id_satellite) REFERENCES SATELLITE (id_satellite),
    CONSTRAINT ck_hist_ancien_statut CHECK (ancien_statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité')),
    CONSTRAINT ck_hist_nouveau_statut CHECK (nouveau_statut IN ('Opérationnel', 'En veille', 'Défaillant', 'Désorbité'))
);

CREATE TABLE INSTRUMENT (
    ref_instrument VARCHAR2(20),
    type_instrument VARCHAR2(50) NOT NULL,
    modele VARCHAR2(100) NOT NULL,
    resolution NUMBER(6,1),
    consommation NUMBER(5,2) NOT NULL,
    masse NUMBER(5,3) NOT NULL,
    CONSTRAINT pk_instrument PRIMARY KEY (ref_instrument),
    CONSTRAINT ck_instrument_type CHECK (type_instrument IN ('Caméra optique', 'Infrarouge', 'Récepteur AIS', 'Spectromètre')),
    CONSTRAINT ck_instrument_resolution CHECK (resolution IS NULL OR resolution > 0),
    CONSTRAINT ck_instrument_conso CHECK (consommation > 0),
    CONSTRAINT ck_instrument_masse CHECK (masse > 0)
);

CREATE TABLE EMBARQUEMENT (
    id_satellite VARCHAR2(20),
    ref_instrument VARCHAR2(20),
    date_integration DATE NOT NULL,
    etat_fonctionnement VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_embarquement PRIMARY KEY (id_satellite, ref_instrument),
    CONSTRAINT fk_emb_satellite FOREIGN KEY (id_satellite) REFERENCES SATELLITE (id_satellite),
    CONSTRAINT fk_emb_instrument FOREIGN KEY (ref_instrument) REFERENCES INSTRUMENT (ref_instrument),
    CONSTRAINT ck_emb_etat CHECK (etat_fonctionnement IN ('Nominal', 'Dégradé', 'Hors service'))
);

CREATE TABLE CENTRE_CONTROLE (
    id_centre NUMBER(10),
    nom_centre VARCHAR2(100) NOT NULL,
    ville VARCHAR2(50) NOT NULL,
    region_geo VARCHAR2(50) NOT NULL,
    fuseau_horaire VARCHAR2(50) NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_centre_controle PRIMARY KEY (id_centre),
    CONSTRAINT uk_centre_nom UNIQUE (nom_centre),
    CONSTRAINT ck_centre_region CHECK (region_geo IN ('Europe', 'Amériques', 'Asie-Pacifique')),
    CONSTRAINT ck_centre_statut CHECK (statut IN ('Actif', 'Inactif'))
);

CREATE TABLE STATION_SOL (
    code_station VARCHAR2(20),
    nom_station VARCHAR2(100) NOT NULL,
    latitude NUMBER(9,6) NOT NULL,
    longitude NUMBER(9,6) NOT NULL,
    diametre_antenne NUMBER(4,1) NOT NULL,
    bande_frequence VARCHAR2(10) NOT NULL,
    debit_max NUMBER(6,1) NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_station_sol PRIMARY KEY (code_station),
    CONSTRAINT ck_station_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_station_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_station_antenne CHECK (diametre_antenne > 0),
    CONSTRAINT ck_station_bande CHECK (bande_frequence IN ('UHF', 'S', 'X', 'Ka')),
    CONSTRAINT ck_station_debit CHECK (debit_max > 0),
    CONSTRAINT ck_station_statut CHECK (statut IN ('Active', 'Maintenance', 'Inactive'))
);

CREATE TABLE AFFECTATION_STATION (
    id_centre NUMBER(10),
    code_station VARCHAR2(20),
    date_affectation DATE NOT NULL,
    CONSTRAINT pk_affectation_station PRIMARY KEY (id_centre, code_station),
    CONSTRAINT fk_aff_centre FOREIGN KEY (id_centre) REFERENCES CENTRE_CONTROLE (id_centre),
    CONSTRAINT fk_aff_station FOREIGN KEY (code_station) REFERENCES STATION_SOL (code_station)
);

CREATE TABLE MISSION (
    id_mission VARCHAR2(20),
    nom_mission VARCHAR2(100) NOT NULL,
    objectif VARCHAR2(500) NOT NULL,
    zone_geo_cible VARCHAR2(200) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE,
    statut_mission VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_mission PRIMARY KEY (id_mission),
    CONSTRAINT ck_mission_statut CHECK (statut_mission IN ('Active', 'Terminée')),
    CONSTRAINT ck_mission_dates CHECK (date_fin IS NULL OR date_fin >= date_debut)
);

CREATE TABLE FENETRE_COM (
    id_fenetre NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 6 INCREMENT BY 1),
    datetime_debut TIMESTAMP NOT NULL,
    duree NUMBER(4) NOT NULL,
    elevation_max NUMBER(5,2) NOT NULL,
    volume_donnees NUMBER(8,1),
    statut VARCHAR2(20) NOT NULL,
    id_satellite VARCHAR2(20) NOT NULL,
    code_station VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_fenetre_com PRIMARY KEY (id_fenetre),
    CONSTRAINT fk_fenetre_satellite FOREIGN KEY (id_satellite) REFERENCES SATELLITE (id_satellite),
    CONSTRAINT fk_fenetre_station FOREIGN KEY (code_station) REFERENCES STATION_SOL (code_station),
    CONSTRAINT ck_fenetre_duree CHECK (duree BETWEEN 1 AND 900),
    CONSTRAINT ck_fenetre_elevation CHECK (elevation_max BETWEEN 0 AND 90),
    CONSTRAINT ck_fenetre_volume CHECK (volume_donnees IS NULL OR volume_donnees >= 0),
    CONSTRAINT ck_fenetre_statut CHECK (statut IN ('Planifiée', 'Réalisée'))
);

CREATE TABLE PARTICIPATION (
    id_satellite VARCHAR2(20),
    id_mission VARCHAR2(20),
    role_satellite VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (id_satellite, id_mission),
    CONSTRAINT fk_part_satellite FOREIGN KEY (id_satellite) REFERENCES SATELLITE (id_satellite),
    CONSTRAINT fk_part_mission FOREIGN KEY (id_mission) REFERENCES MISSION (id_mission)
);

SELECT table_name
FROM user_tables
WHERE table_name IN (
    'ORBITE', 'SATELLITE', 'HISTORIQUE_STATUT', 'INSTRUMENT', 'EMBARQUEMENT',
    'CENTRE_CONTROLE', 'STATION_SOL', 'AFFECTATION_STATION', 'MISSION',
    'FENETRE_COM', 'PARTICIPATION'
)
ORDER BY table_name;
